language: ruby

rvm:
  - 2.4.1

bundler_args: --without production

cache: bundler

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - ./bin/rails db:create
  - ./bin/rails db:migrate

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5e88c507b05f867f94a
    on_success: change
    on_failure: always
    on_start: never
