language: ruby

services:
  - postgresql

cache: bundler

bundler_args: --without production --deployment

before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:create

script:
  - bin/rails spec

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5e88c507b05f867f94a
